
server.port=8080
spring.application.name=uco-finca-backend


spring.datasource.url=jdbc:sqlserver://localhost:14330;databaseName=uco_finca;integratedSecurity=true;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver



spring.jpa.hibernate.ddl-auto=none


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


spring.sql.init.mode=never
