server.port=8080
spring.application.name=uco-finca-backend

# ===============================
# SQL SERVER
# ===============================

spring.datasource.url=jdbc:sqlserver://localhost:14330;databaseName=uco_finca;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===============================
# SQL INIT
# ===============================

spring.sql.init.mode=never

# ===============================
# LOGS
# ===============================

logging.level.root=WARN
logging.level.co.edu.uco.ucoparking=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE